### ISSUE TITLE
Getting ready for the Proactive Controls 2023

### ISSUE THREAD

**Issue by jmanico** [OWASP/www-project-proactive-controls#20]
Here is the first take of an OWASP Top Ten like Proactive List.

P01 - Implement Access Controls
P02 - Protect Data
P03 - Stop Injection
P04 - Do Design Review and Threat Modeling
P05 - Implement Good Security Configuration
P06 - Keep your Components Updated
P07 - Implement Digital Identity
P08 - Implement Data Integrity
P09 - Implement Security Logging
P10 - Stop Server Side Request Forgery

cc @katyanton

**Comment by cesarkohl** [comment]
It was time!

**Comment by andreashappe** [comment]
a preliminary version can be found at https://github.com/OWASP/www-project-proactive-controls/tree/v4-initial-version

Any help would be appreciated (: cheers, Andreas

**Comment by andreashappe** [comment]
let's move this to the pull request for the new version: https://github.com/OWASP/www-project-proactive-controls/pull/27
