### ISSUE TITLE
outdated references

### ISSUE THREAD

**Issue by wittjoe1** [OWASP/www-project-proactive-controls#26]
Hi,

I just found that outdated references are included in the [c4-encode-escape-data](https://github.com/OWASP/www-project-proactive-controls/blob/master/v3/en/c4-encode-escape-data.md).
References going to the zend framework (zend-escaper) are outdated since 2018 as the project has opened within the laminas project. The reference should be updated to https://docs.laminas.dev/laminas-escaper/

Thx Jörg

**Comment by andreashappe** [comment]
Hi,
we're currently preparing v4 of the controls and zend-escaper is not mentioned in there anymore (just grep'ed it). I would keep the reference in the "historic" v3 guide though. You can find the new version in the 'v4-initial-version' branch if you want to take a look at it.

cheers and thank you,
Andreas
