### ISSUE TITLE
C2: Use Cryptography the proper way - Cryptographic Agility

### ISSUE THREAD

**Issue by julienr78** [OWASP/www-project-proactive-controls#29]
While this is briefly covered here: "make cryptographic choices such as used algorithms or key sizes configurable". The upcoming Quantum threat really puts a huge emphasis on this. The industry uses "Cryptographic Agility" as the term, which is defined here:
https://en.wikipedia.org/wiki/Cryptographic_agility

**Comment by andreashappe** [comment]
Good point, do you want to create an update (pull request) for v4? I would de-empathize the quantum angle (to not feed the "quantum supremacy is a hype" crowd) as cryptographic agility is a good idea by itself anyways.

cheers, Andreas

**Comment by andreashappe** [comment]
added
