### ISSUE TITLE
C8, the browser, is not universal

### ISSUE THREAD

**Issue by adamshostack** [OWASP/www-project-proactive-controls#31]
Not every project uses 'the browser'; there's IoT, apps, and other things. Is there a broader framing?

**Comment by andreashappe** [comment]
The browser and/or HTTP clients (including libraries)? TBH, it is not very clear which HTTP header actually are in use by the different non-browser environments.

**Comment by andreashappe** [comment]
added a small paragraph at the beginning that should highlight this.
