### ISSUE TITLE
Missing concept: Make it easy to do the right thing

### ISSUE THREAD

**Issue by RichardoC** [OWASP/www-project-proactive-controls#34]
While this is similar to <https://owasp.org/www-project-proactive-controls/v4/en/c5.html> I've found one of the most effective proactive controls is making it easy for folks to do the right thing. This is true both for developers and for users.

For example, rather than each team having to write their own authentication, use an existing library which is pre-configured with best practises. Another example would be defaulting to time limited access and strong authentication, and having it be a deliberate change by a user to reduce the security of these settings.

**Comment by andreashappe** [comment]
hm, maybe we could add this to #32 ?

more or less I would like to have a 'c8: get fundamental architecture right' chapter, including:

- document architecture including security boundaries
- kiss principle for maintenance and transparency
- the 'make it easy to do the right thing' might be well fitting there too

**Comment by RichardoC** [comment]
Yeah, it could fit there nicely in the fundamental architecture section. Was just hoping for the sound bite of a chapter title "Make it easy to do the right thing" as that phrase has helped a lot with some teams! It may not be worth it though

**Comment by andreashappe** [comment]
I've created a branch and started with some restructuring: https://github.com/OWASP/www-project-proactive-controls/blob/rewrite-secure-architecture/v4/en/c4-secure-architecture.md

I added a high-level overview to the 'design' section about general principles and added some of the mentioned topics in 'implementation'. The previous 'use architecture patterns' is now a subsection in the 'implementation' section, maybe it should also be mentioned in 'description' like "don't reinvent the wheel".

Commits to that branch that flesh out the different areas would be highly appreciated (;

**Comment by RichardoC** [comment]
Closed by #51
