### ISSUE TITLE
C7: Implement Digital Identity

### ISSUE THREAD

**Issue by vdbaan** [OWASP/www-project-proactive-controls#46]
under heading 'Authentication Assurance Levels' the text does not flow.

In the first paragraph you mention AAL and the definition of AAL Level 1. 
Then the sentence mentions single factor authentication and 'something you know' and then leads to 3 bullet points (where I expected something you know, something you have and something you are). But these bullet points shortly describe AAL2 and AAL3. 

And then AAL2 and AAL3 are described further in detail.

I would recommend reorganising this part.

**Comment by andreashappe** [comment]
(hopefully) fixed.
