### ISSUE TITLE
#C4 Secure Architecture Patterns - enemy of enemy

### ISSUE THREAD

**Issue by wittjoe1** [OWASP/www-project-proactive-controls#53]
Hi,

In line 34 the "mantra" "Complexity is the enemy of enemy of security" is quoted. In other words: "complexity promotes security".
Unfortunately, this contradicts the rest of the intended content: the more complexity, the less security.
Correctly it should be "simplicity is the enemy of the enemy of security" or "Complexity is the enemy of enemy of hackers"...
Otherwise - to say it with a KISS: "Complexity is the enemy of security" :-)

What do you think about this?

**Comment by andreashappe** [comment]
haha (: do you want to sent a merge-request for that (: otherwise I can do a quick-fix if that's easier for you

**Comment by andreashappe** [comment]
already fixed
