### ISSUE TITLE
Broken links in OWASP Proactive Controls web page

### ISSUE THREAD

**Issue by srcnuzn** [OWASP/www-project-proactive-controls#54]
1. Open https://top10proactive.owasp.org/
2. Click on [C1: Define Security Requirements](https://top10proactive.owasp.org/www-project-proactive-controls/v3/en/c1-security-requirements)

Expected: Page opens
Actual: Error 404

**Comment by andreashappe** [comment]
Hi, we're currently preparing a new version and switching to another site-generator. This should be fixed in the next couple of days. Thank you for your report

**Comment by andreashappe** [comment]
Should be fixed (now also in the old version)

**Comment by srcnuzn** [comment]
Just verified, links work again.
