### ISSUE TITLE
check v3 markdown files, move information to cheat sheet series and, remove them from the project

### ISSUE THREAD

**Issue by andreashappe** [OWASP/www-project-proactive-controls#59]
we still have the doc/pdfs from the 2018/`v3` series stored. The markdown files in `v3/en` are not used by anything.

Check if some of the content from the v3 version could be moved to the owasp cheat sheet series. If so, move it there and remove the markdown files from this project.

**Comment by jgadsden** [comment]
It would be good to be able to keep the 2014 and 2018 versions of the proactive controls. There may be references to them from other sites / projects that are still valid, even with the latest version of controls coming out

**Comment by andreashappe** [comment]
the 2014 versions seem to be doc/pdf only. 

I am checking incoming links to the website and also would like to preserve old versions. One problem is an ongoing bug within `mkdocs` that prevents generating similar URLs (as were used before). I have it on my todo list, but more or less am waiting what mkdocs is doing.

**Comment by andreashappe** [comment]
By now 2014/2016/2018 versions are available, but still need to find a way to remap incoming links (as this does not seem possible with `mkdocs` itself).
