### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by twojnarowski** [OWASP/www-project-proactive-controls#6]
On this website: https://owasp.org/www-project-proactive-controls/v3/en/c9-security-logging

All links in "References" lead to a 404 error. Also last bullet point in "Logging for Intrusion Detection and Response" and 4th bullet point of "References" seem to have broken code. 
I add screenshot of broken code for link:
![image](https://user-images.githubusercontent.com/13180578/120079694-63264c80-c0b5-11eb-90ea-5599d961a2e7.png)
And the links that lead to a 404:
![image](https://user-images.githubusercontent.com/13180578/120079707-6cafb480-c0b5-11eb-8373-48d160d03dc4.png)

**Comment by jmanico** [comment]
Thank you. I’ll get this fixed.

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
All fixed https://owasp.org/www-project-proactive-controls/v3/en/c9-security-logging
