### ISSUE TITLE
remove/integrate `tab_numbers.md`

### ISSUE THREAD

**Issue by andreashappe** [OWASP/www-project-proactive-controls#60]
this should be the final document from the `v3` version

**Comment by jgadsden** [comment]
Is it possible to keep the permalinks to v3?

**Comment by andreashappe** [comment]
not 100% sure, as `mkdocs` currently not allows this out-of-the-box. We might be able to do something with redirects, but that would need to be setup by the webserver by OWASP (not by us within the github repo)

**Comment by andreashappe** [comment]
this issue should be resolved with the latest online version, we still need to solve the redirects (but this is another issue).
